[package]
name = "invaders"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.0"
crossterm = "0.17.5"
rusty_audio = "1.1.4"
rusty_time = "0.11.0"

[profile.dev.package."*"]
opt-level = 3